# 1.5.1. ファイル入出力: scipy.io

In [2]:
import numpy as np
from scipy import io as spio
a = np.ones((3, 3))
spio.savemat('file.mat', {'a': a}) # savemat expects a dictionary
data = spio.loadmat('file.mat', struct_as_record=True)
data['a']

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [4]:
from scipy import misc
# misc.imread('fname.png') 

In [5]:
import matplotlib.pyplot as plt
# plt.imread('fname.png') 

# 1.5.2. 特殊関数: scipy.special

# 1.5.3. 線形代数演算: scipy.linalg

- scipy.linalg.det() 関数は正方行列の 行列（determinant） を計算

In [18]:
from scipy import linalg
arr = np.array([[1, 2], [3, 4]])
linalg.det(arr)

-2.0

In [20]:
# linalg.det(np.ones((3, 4)))

In [17]:
arr = np.array([[3, 2], [6, 4]])
linalg.det(arr)

6.661338147750939e-16

- scipy.linalg.inv() 関数は正方行列の逆行列を計算

In [22]:
arr = np.array([[1, 2], [3, 4]])
iarr = linalg.inv(arr)
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
np.allclose(np.dot(arr, iarr), np.eye(2))

True

- より高度な操作も利用可能です、例: 特異値分解(SVD)

In [26]:
arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1])
arr

array([[1, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

In [27]:
uarr, spec, vharr = linalg.svd(arr)
print(uarr)
print(spec)
print(vharr)

[[-0.1617463  -0.98659196  0.02178164]
 [-0.47456365  0.09711667  0.87484724]
 [-0.86523261  0.13116653 -0.48390895]]
[ 14.88982544   0.45294236   0.29654967]
[[-0.45513179 -0.54511245 -0.70406496]
 [ 0.20258033  0.70658087 -0.67801525]
 [-0.86707339  0.45121601  0.21115836]]


- 元々の行列は svd の出力を np.dot の行列積によって再構成することができます:

In [28]:
sarr = np.diag(spec)
svd_mat = uarr.dot(sarr).dot(vharr)
np.allclose(svd_mat, arr)

True

SVD は統計や信号解析によく利用されます。線形システムにおける多くの標準的な分解(QR, LU, Cholesky, Schur) も同様に scipy.linalg で利用可能です。

