In [36]:
!ls

base			discriminator_model_200   facades.zip	   result
CMP_facade_DB_base.zip	drive			  googledrive
datalab			encoderdecoder_model_200  label_names.txt
dataset			facades			  readme.txt


In [37]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms xsaveopt
bugs		:
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 4

In [39]:
!cat /proc/meminfo

MemTotal:       13341960 kB
MemFree:         1623328 kB
MemAvailable:   10390284 kB
Buffers:          685536 kB
Cached:          7714864 kB
SwapCached:            0 kB
Active:          5370796 kB
Inactive:        5162048 kB
Active(anon):    2211208 kB
Inactive(anon):   277648 kB
Active(file):    3159588 kB
Inactive(file):  4884400 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               284 kB
Writeback:             0 kB
AnonPages:       2132532 kB
Mapped:           458496 kB
Shmem:            356424 kB
Slab:            1010512 kB
SReclaimable:     976384 kB
SUnreclaim:        34128 kB
KernelStack:        3584 kB
PageTables:        10500 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6670980 kB
Committed_AS:    3768044 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
AnonHugePages:         0 kB
HugePages_Total: 

In [40]:
!ls /proc/

1     buddyinfo  execdomains  kpagecgroup   partitions	   timer_list
2322  bus	 filesystems  kpagecount    schedstat	   tty
2364  cgroups	 fs	      kpageflags    scsi	   uptime
2394  cmdline	 interrupts   loadavg	    self	   version
3001  config.gz  iomem	      locks	    slabinfo	   vmallocinfo
3444  consoles	 ioports      meminfo	    softirqs	   vmstat
3469  cpuinfo	 irq	      misc	    stat	   zoneinfo
3470  crypto	 kallsyms     modules	    swaps
73    devices	 kcore	      mounts	    sys
83    diskstats  keys	      mtrr	    sysrq-trigger
93    dma	 key-users    net	    sysvipc
acpi  driver	 kmsg	      pagetypeinfo  thread-self


In [41]:
!cat /proc/devices

Character devices:
  1 mem
  4 ttyS
  5 /dev/tty
  5 /dev/console
  5 /dev/ptmx
 10 misc
 13 input
128 ptm
136 pts
195 nvidia-frontend
202 cpu/msr
203 cpu/cpuid
249 nvidia-uvm
250 nvlink_core
251 bsg
252 watchdog
253 rtc
254 tpm

Block devices:
259 blkext
  7 loop
  8 sd
 65 sd
 66 sd
 67 sd
 68 sd
 69 sd
 70 sd
 71 sd
128 sd
129 sd
130 sd
131 sd
132 sd
133 sd
134 sd
135 sd
254 device-mapper


In [42]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 387804808179971691, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 8794610074
 locality {
   bus_id: 1
 }
 incarnation: 4458354524980433792
 physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7"]

# googleドライブをマウントする

In [18]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


# wgetでデータをとる

In [23]:
!wget https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/Titanic.csv -P drive/app

--2018-03-06 11:22:22--  https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/Titanic.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70366 (69K) [text/plain]
Saving to: ‘drive/app/Titanic.csv’

Titanic.csv         100%[===================>]  68.72K  --.-KB/s    in 0.03s   

2018-03-06 11:22:22 (2.31 MB/s) - ‘drive/app/Titanic.csv’ saved [70366/70366]



In [24]:
import pandas as pd
titanic = pd.read_csv("drive/app/Titanic.csv")
titanic.head(5)

Unnamed: 0                                           Name PClass    Age  \
0           1                   Allen, Miss Elisabeth Walton    1st  29.00   
1           2                    Allison, Miss Helen Loraine    1st   2.00   
2           3            Allison, Mr Hudson Joshua Creighton    1st  30.00   
3           4  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00   
4           5                  Allison, Master Hudson Trevor    1st   0.92   

      Sex  Survived  SexCode  
0  female         1        1  
1  female         0        1  
2    male         0        0  
3  female         0        1  
4    male         1        0

In [0]:
!mkdir googledrive

In [0]:
!google-drive-ocamlfuse googledrive

In [6]:
!ls

datalab  sample.csv


In [0]:
!pip install --upgrade -q gspread

In [9]:
%ls

base/                   dataset/                  facades/         readme.txt
CMP_facade_DB_base.zip  discriminator_model_200   facades.zip      result/
datalab/                encoderdecoder_model_200  label_names.txt


In [5]:
!ls

datalab


In [1]:
!apt -y install libcusparse8.0 libnvrtc8.0 libnvtoolsext1
!ln -snf /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so.8.0 /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so
!pip install 'cupy-cuda80==4.0.0b4' 'chainer==4.0.0b4'

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcusparse8.0 is already the newest version (8.0.61-1).
libnvrtc8.0 is already the newest version (8.0.61-1).
libnvtoolsext1 is already the newest version (8.0.61-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
    99% |████████████████████████████████| 204.7MB 46.5MB/s eta 0:00:01tcmalloc: large alloc 1092009984 bytes == 0x5582ee9cc000 @  0x7f622a97c107 0x55829d85b4ed 0x55829d8deac0 0x55829d903d29 0x55829d86290e 0x55829d927021 0x55829d87977a 0x55829d87e462 0x55829d876b3a 0x55829d87e82e 0x55829d876b3a 0x55829d892809 0x55829d8ab56e 0x55829d86290e 0x55829d8f3b76 0x55829d87e650 0x55829d87e462 0x55829d876b3a 0x55829d87e82e 0x55829d876b3a 0x55829d87e82e 0x55829d891d68 0x55829d879c3f 0x55829d891d68 0x55829d879c3f 0x55829d891d68 0x55829d879c3f 0x55829d891d68 0x55829d879c3f 0x55829d876b3a 0x55829d87ee1f
    100% |████████████████████████████████| 204.8MB 5.6kB/s 
    100% |██████

- done
  Stored in directory: /content/.cache/pip/wheels/5f/5e/8a/9f1eb481ffbfff95d5f550570c1dbeff3c1785c8383c12c62b
Successfully built chainer filelock


In [0]:
#https://qiita.com/danpansa/items/29cea2b14c0e4db237f8
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data
X = X.astype(np.float32)

Y = iris.target
Y = Y.flatten().astype(np.int32)


In [4]:
X[[0]]

array([[5.1, 3.5, 1.4, 0.2]], dtype=float32)

In [5]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [6]:
import chainer
import chainer.functions as F
import chainer.links as L
from chainer import training, datasets
from chainer.training import extensions
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
X = X.astype(np.float32)
Y = iris.target
Y = Y.flatten().astype(np.int32)

train ,test= datasets.split_dataset_random(chainer.datasets.TupleDataset(X,Y),100)
train_iter = chainer.iterators.SerialIterator(train, 10)
test_iter = chainer.iterators.SerialIterator(test, 1,repeat=False, shuffle=False)

class IrisModel(chainer.Chain):
    def __init__(self):
        super(IrisModel,self).__init__(
                l1 = L.Linear(4,100),
                l2 = L.Linear(100,100),
                l3 = L.Linear(100,3))

    def __call__(self,x):    
         h = F.relu(self.l1(x))
         h = F.relu(self.l2(h))
         return self.l3(h)

model = L.Classifier(IrisModel())
optimizer = chainer.optimizers.Adam()
optimizer.setup(model)

updater = training.StandardUpdater(train_iter, optimizer, device=-1)
trainer = training.Trainer(updater, (30, 'epoch'), out="result")
trainer.extend(extensions.Evaluator(test_iter, model, device=-1))
trainer.extend(extensions.LogReport())
trainer.extend(extensions.PrintReport( ['epoch', 'main/loss', 'validation/main/loss', 'main/accuracy', 'validation/main/accuracy']))
trainer.extend(extensions.ProgressBar())

trainer.run()

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy
1           1.01887     0.756855              0.44           0.58                      
2           0.627109    0.498615              0.8            0.84                      
3           0.463068    0.394306              0.87           0.94                      
4           0.382007    0.308501              0.96           1                         
5           0.321678    0.39092               0.93           0.7                       
6           0.300294    0.242048              0.91           1                         
7           0.27175     0.223351              0.91           1                         
8           0.232472    0.266516              0.96           0.88                      
9           0.229135    0.182057              0.97           1                         
10          0.213276    0.26437               0.94           0.86                      
     total [################......

In [8]:
!ls out

log


In [9]:
F.softmax(np.array([test[0][0]])).data

array([[0.82856786, 0.13696131, 0.02765202, 0.0068189 ]], dtype=float32)

In [10]:
F.softmax(np.array([test[0][0]])).data.argmax(axis=1)

array([0])

In [0]:
y = model.predictor(np.array([[1,  1,  1,  1  ]]).astype(np.float32))

In [12]:
F.softmax(y).data

array([[0.09460501, 0.13254933, 0.7728457 ]], dtype=float32)

In [13]:
F.softmax(y).data.argmax(axis=1)

array([2])

In [1]:
! git clone

fatal: You must specify a repository to clone.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          u