# 算術記号とTensorFlow関数の対応


https://www.saintsouth.net/blog/map-of-arithmetic-symbols-and-tensorflows-function/

## 演算対象のテンソルxの定義


In [32]:
import tensorflow as tf

x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = x  # この行を置き換えて確認します。

with tf.Session() as sess:
    print(sess.run(y))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## tf.negative 符号反転

$y=-x$

In [4]:
y = tf.negative(x)
with tf.Session() as sess:
    print(sess.run(y))

[[-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]]


## tf.abs 絶対値

$y=\left | x \right |$

In [5]:
y = tf.abs(x)
with tf.Session() as sess:
    print(sess.run(y))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## tf.reciprocal 逆数

$y=\frac{1}{x}$

In [7]:
y = tf.reciprocal(x)
with tf.Session() as sess:
    print(sess.run(y))

[[1.         0.5        0.33333334]
 [0.25       0.2        0.16666667]
 [0.14285715 0.125      0.11111111]]


## tf.square 2乗

$y=x^2$

In [8]:
y = tf.square(x)
with tf.Session() as sess:
    print(sess.run(y))

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


## tf.sqrt べき根

$y=\sqrt{x}$

In [9]:
y = tf.sqrt(x)
with tf.Session() as sess:
    print(sess.run(y))

[[0.99999994 1.4142134  1.7320508 ]
 [1.9999999  2.236068   2.4494896 ]
 [2.6457512  2.8284268  3.        ]]


## tf.rsqrt べき根の逆数

$y=\frac{1}{\sqrt{x}}$

In [10]:
y = tf.rsqrt(x)
with tf.Session() as sess:
    print(sess.run(y))

[[0.99999994 0.7071067  0.57735026]
 [0.49999997 0.4472136  0.40824828]
 [0.37796447 0.35355335 0.33333334]]


## tf.exp 指数

$y=e^x$

In [11]:
y = tf.exp(x)
with tf.Session() as sess:
    print(sess.run(y))

[[2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342877e+02]
 [1.0966332e+03 2.9809580e+03 8.1030840e+03]]


## tf.log 自然対数

$y=log_{e}x$

In [12]:
y = tf.log(x)
with tf.Session() as sess:
    print(sess.run(y))

[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]
 [1.9459102 2.0794415 2.1972246]]


## tf.reduce_sum 総和

reduce_sum はテンソルの任意の次元の要素を足し合わせて新しいテンソルを返します。何次元目を足し合わせるかは、第2引数またはreduction_indicesで指定します。指定がなければすべての次元で足し合わせて、1つの値を返します。

### i(1次元目)で足し合わせ

$y=\sum_{i=1}^{m}x_{ij}$

In [13]:
y = tf.reduce_sum(x, 0)
with tf.Session() as sess:
    print(sess.run(y))

[12. 15. 18.]


### j(2次元目)で足し合わせ

$y=\sum_{j=1}^{m}x_{ij}$

In [3]:
y = tf.reduce_sum(x, 1)
with tf.Session() as sess:
    print(sess.run(y))

[ 6. 15. 24.]


### すべての次元で足し合わせ

$y=\sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}$

In [4]:
y = tf.reduce_sum(x)
with tf.Session() as sess:
    print(sess.run(y))

45.0


## tf.reduce_prod 総乗

reduce_sum はテンソルの任意の次元の要素をかけ合わせて新しいテンソルを返します。何次元目をかけ合わせるかは、第2引数またはreduction_indicesで指定します。指定がなければすべての次元でかけ合わせて、1つの値を返します。

### i(1次元目)でかけ合わせ

$y=\prod_{i=1}^{m}x_{ij}$

In [5]:
y = tf.reduce_prod(x, 0)
with tf.Session() as sess:
    print(sess.run(y))

[ 28.  80. 162.]


### j(2次元目)でかけ合わせ

$y=\prod_{j=1}^{n}x_{ij}$

In [6]:
y = tf.reduce_prod(x, 1)
with tf.Session() as sess:
    print(sess.run(y))

[  6. 120. 504.]


### すべての次元でかけ合わせ

In [7]:
y = tf.reduce_prod(x)
with tf.Session() as sess:
    print(sess.run(y))

362880.0


## tf.reduce_mean 平均

reduce_mean はテンソルの任意の次元の要素の平均を計算して、新しいテンソルを返します。何次元目の平均をとるかは、第2引数またはreduction_indicesで指定します。指定がなければすべての次元の要素の平均を計算して、1つの値を返します。

### i(1次元目)の平均

$y=\frac{1}{m}\sum_{i=1}^{m}x_{ij}$

In [8]:
y = tf.reduce_mean(x, 0)
with tf.Session() as sess:
    print(sess.run(y))

[4. 5. 6.]


### j(2次元目)の平均

$y=\frac{1}{n}\sum_{j=1}^{m}x_{ij}$

In [9]:
y = tf.reduce_mean(x, 1)
with tf.Session() as sess:
    print(sess.run(y))

[2. 5. 8.]


### すべての次元の平均

$y=\frac{1}{mn}\sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}$

In [10]:
y = tf.reduce_mean(x)
with tf.Session() as sess:
    print(sess.run(y))

5.0


## tf.reduce_all　bool処理

今までの要領でand条件でbool処理を行う。全要素にTrueが入ってるとTrueになる。

In [13]:
x = tf.constant([[True,  True], [False, False]])
y1 = tf.reduce_all(x)  # False
y2 = tf.reduce_all(x, 0)  # [False, False]
y3 = tf.reduce_all(x, 1)  # [True, False]
with tf.Session() as sess:
    print(sess.run(y1))
    print(sess.run(y2))
    print(sess.run(y3))

False
[False False]
[ True False]


In [18]:
x = tf.constant([[True,  True], [True, True]])
y1 = tf.reduce_all(x)  # True
y2 = tf.reduce_all(x, 0)  # [True, False]
y3 = tf.reduce_all(x, 1)  # [True, True]
with tf.Session() as sess:
    print(sess.run(y1))
    print(sess.run(y2))
    print(sess.run(y3))

True
[ True  True]
[ True  True]


## tf.reduce_any

or条件でTrue要素が一つでもあればTrueになる。

In [16]:
x = tf.constant([[True,  True], [False, False]])
y1 = tf.reduce_any(x)  # True
y2 = tf.reduce_any(x, 0)  # [True, True]
y3 = tf.reduce_any(x, 1)  # [True, False]
with tf.Session() as sess:
    print(sess.run(y1))
    print(sess.run(y2))
    print(sess.run(y3))

True
[ True  True]
[ True False]


## tf.reduce_join

In [27]:
x = tf.constant([["a",  "b"], ["c", "d"]])
y1 = tf.reduce_join(x, 0) # ["ac", "bd"]
y2 = tf.reduce_join(x, 1) # ["ab", "cd"]
y_a1 = tf.reduce_join(x, -2) # ["ac", "bd"]
y_a2 = tf.reduce_join(x, 0) # ["ac", "bd"]
y_b1 = tf.reduce_join(x, -1)
y_b2 = tf.reduce_join(x, 1)


with tf.Session() as sess:
    print("=======")
    print(sess.run(y1))
    print(sess.run(y2))
    print("=======")
    print(sess.run(y_a1))
    print(sess.run(y_a2))
    print("=======")
    print(sess.run(y_b1))
    print(sess.run(y_b2))

[b'ac' b'bd']
[b'ab' b'cd']
[b'ac' b'bd']
[b'ac' b'bd']
[b'ab' b'cd']
[b'ab' b'cd']


## tf.reduce_logsumexp

log(sum(exp(テンソル次元間の要素)))

In [31]:
x = tf.constant([[0., 0., 0.], [0., 0., 0.]])
y1 = tf.reduce_logsumexp(x)  # log(6)
y2 = tf.reduce_logsumexp(x, 0)  # [log(2), log(2), log(2)]
y3 = tf.reduce_logsumexp(x, 1)  # [log(3), log(3)]
y4 = tf.reduce_logsumexp(x, 1, keepdims=True)  # [[log(3)], [log(3)]]
y5 = tf.reduce_logsumexp(x, [0, 1])  # log(6)

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))
    print(sess.run(y2))
    print(sess.run(y3))
    print(sess.run(y4))
    print(sess.run(y5))

[[0. 0. 0.]
 [0. 0. 0.]]
1.7917595
[0.6931472 0.6931472 0.6931472]
[1.0986123 1.0986123]
[[1.0986123]
 [1.0986123]]
1.7917595


## tf.argmax

axisはデフォルトは0。

In [40]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
y1 = tf.argmax(x)
y2 = tf.argmax(x, 0)
y3 = tf.argmax(x, 1)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))
    print(sess.run(y2))
    print(sess.run(y3))

[[1 2 3]
 [4 5 6]]
[1 1 1]
[1 1 1]
[2 2]


列方向に比較    
[7,,]と[8,,]を比較。[,7,]と[,8,]を比較。

In [44]:
x = tf.constant([[7, 7, 7], [8, 8, 8]])
y1 = tf.argmax(x)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))

[[7 7 7]
 [8 8 8]]
[1 1 1]


In [45]:
x = tf.constant([[8, 8, 8], [7, 7, 7]])
y1 = tf.argmax(x)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))

[[8 8 8]
 [7 7 7]]
[0 0 0]


行方向に比較?    
[7, 7, 7]の中で一番大きいの。


In [46]:
x = tf.constant([[7, 7, 7], [8, 8, 8]])
y1 = tf.argmax(x, 1)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))

[[7 7 7]
 [8 8 8]]
[0 0]


In [48]:
x = tf.constant([[1, 2, 3], [1,3,2], [3, 2, 1]])
y1 = tf.argmax(x, 1)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))

[[1 2 3]
 [1 3 2]
 [3 2 1]]
[2 1 0]


## tf.argmin

In [41]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
y1 = tf.argmin(x)
y2 = tf.argmin(x, 0)
y3 = tf.argmin(x, 1)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y1))
    print(sess.run(y2))
    print(sess.run(y3))

[[1 2 3]
 [4 5 6]]
[0 0 0]
[0 0 0]
[0 0]


## tf.cast

In [51]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
y = tf.cast(x, tf.int32)  # [1, 2], dtype=tf.int32
with tf.Session() as sess:
    print(sess.run(x).dtype)
    print(sess.run(y).dtype)

float32
int32
