In [1]:
#http://www.procrasist.com/entry/2-100-numpy-exercise

In [3]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.random.random(5)

array([0.95260174, 0.56107685, 0.60595872, 0.45112928, 0.06073313])

In [9]:
np.random.randint(0,5,10)

array([1, 4, 1, 2, 3, 2, 2, 4, 2, 1])

In [10]:
np.random.uniform(0,1,5)

array([0.50275518, 0.71222331, 0.71753565, 0.38599458, 0.38467379])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
A = np.zeros((5,5), [('x',float), ('y',float)])

In [14]:
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))

In [15]:
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [26]:
def generate():
    for x in range(10):
        yield x

In [27]:
a = np.fromiter(generate(), dtype=float, count=-1)

In [28]:
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [29]:
def generate():
    for x in range(10):
        return x

In [30]:
a = np.fromiter(generate(), dtype=float, count=-1)

TypeError: 'int' object is not iterable

In [31]:
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [33]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])