In [ ]:
#https://docs.scipy.org/doc/numpy/reference/index.html

# The N-dimensional array

In [37]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


# Universal functions

## Broadcasting

## Casting Rules

# numpy.random.rand

In [61]:
import random
import math
print(np.random.rand(3,2))
print(np.random.rand(1)[0])


print(random.random())
print(round(random.random()))

# x = rd.rand(2, 3)
print(np.random.choice(10, 1, replace=False )[0])

[[ 0.71275871  0.80761803]
 [ 0.63474119  0.10864041]
 [ 0.46017675  0.89452025]]
0.0661829268853
0.07184601556985193
1
7


In [53]:
import math
round(np.random.rand(1)[0])

1.0

# numpy.newaxis

In [3]:
import numpy as np
#縦ベクトルへの変換
a = np.array([1,2,3,4,5])
b = a[:,np.newaxis]
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [4]:
c = a[:,None]
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]]
