In [ ]:
#http://postd.cc/linear-algebra-cheat-sheet-for-deep-learning/

線形代数は、複雑な問題を単純で直感的に理解できる、計算効率の良い問題に変換してくれます。以下は、線形代数を使えばいかに高速で単純な解法を導くことができるかを示す例です。



In [3]:
import numpy
# 2つの配列を掛ける 
x = [1,2,3]
y = [2,3,4]
product = []
for i in range(len(x)):
    product.append(x[i]*y[i])
# 線形代数バージョン
x = numpy.array([1,2,3])
y = numpy.array([2,3,4])
x * y

#numpyライブラリのブロードキャスト機能って認識だったけども。。。


array([ 2,  6, 12])

# ベクトル

## 要素ごとの演算

In [6]:
y = np.array([1,2,3])
x = np.array([2,3,4])
print(y + x)
print(y - x) 
print(y / x)

[3 5 7]
[-1 -1 -1]
[ 0.5         0.66666667  0.75      ]


## 内積

In [9]:
y = numpy.array([1,2,3])
x = numpy.array([2,3,4])
numpy.dot(y,x)

20

## アダマール積

要素ごとの積

In [10]:
y = np.array([1,2,3])
x = np.array([2,3,4])
y * x

array([ 2,  6, 12])

## 行列の次元

In [12]:
a = np.array([
 [1,2,3], 
 [4,5,6]
])
print(a.shape)
b = np.array([
 [1,2,3]
])
print(b.shape)


(2, 3)
(1, 3)


## 行列のスカラー演算

In [14]:
a = np.array(
[[1,2], 
 [3,4]])
print(a + 1)

[[2,3], 
 [4,5]]

[[2 3]
 [4 5]]


[[2, 3], [4, 5]]

## 行列の転置

In [18]:
a = np.array([
   [1, 2], 
   [3, 4]])
a.T

array([[1, 3],
       [2, 4]])

In [19]:
a = np.array([
 [1, 2]
 ])
a.shape == (1,2)
b = np.array([
 [3, 4],
 [5, 6]
 ])
b.shape == (2,2)
# 掛ける
mm = np.dot(a,b)
mm == [13, 16]
mm.shape == (1,2)

True